services:
  backend:
    build: ./ORION-BACKEND
    container_name: yarbis-backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend/model:/app/model
    restart: always

  frontend:
    build: ./ORION-FRONTEND
    container_name: yarbis-frontend
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./certs:/etc/nginx/ssl
    restart: always